#!/usr/bin/env node
const p = require('./freemat.js');
const fs = require('fs');
const txt = fs.readFileSync(process.argv[2], 'utf8');
console.log(`parse string:\n***\n${txt}***\n`);
const y = p.parse(txt);
console.log(JSON.stringify(y, null, 2));
